#!/usr/bin/env bash
#this script will add a http response header string 
new_string="add_header  X-Served-By  3-web-01;\n# First attempt to serve request as file, then"
ssh ubuntu@35.231.236.13 "sudo sed -i \"s/# First attempt to serve request as file, then/${new_string}/\" /etc/nginx/sites-enabled/default && sudo service nginx restart "
new_string1="add_header  X-Served-By  3-web-02;\n# First attempt to serve request as file, then"
ssh ubuntu@35.231.53.147 "sudo sed -i \"s/# First attempt to serve request as file, then/${new_string1}/\" /etc/nginx/sites-enabled/default && sudo service nginx restart "

