#!/usr/bin/env bash
# install haproxy and congigure it
sudo apt-get update -y 
sudo apt-get install haproxy -y
new_string=$'\n
frontend http\n
\tbind *:80\n
\tmode http\n
\tdefault_backend web-backend\n
backend web-backend\n
\tbalance roundrobin\n
\tserver 3132-web-01 35.231.236.13:80 check\n
\tserver 3132-web-02 35.231.53.147:80 check'
echo "$new_string" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" |sudo tee -a /etc/default/haproxy
sudo service haproxy restart

