#!/usr/bin/env bash
#this script is installin nginx in configure port 80 and editing the intex file to return string
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chmod a+rw /var/www/html/index.nginx-debian.html
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo service nginx restart

