#!/usr/bin/env bash
#this script is installin nginx and add a 301 rediraction to the default configuration file
sudo apt-get update -y
sudo apt-get install nginx -y
new_string="location \/redirect_me {\nreturn 301 'https:\/\/www.youtube.com\/watch?v=lTRiuFIWV54';\n}\nlocation"
sed -i "s/location/${new_string}/" /etc/nginx/sites-enabled/default
sudo service nginx restart

