#!/usr/bin/env bash
#this script is installin nginx and add a 301 rediraction to the default configuration file
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chmod a+rw /var/www/html/index.nginx-debian.html
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo touch /var/www/html/error_404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null
new_string="server_name _;\nerror_page 404 \/error_404.html;\n"
sudo sed -i "s/server_name _;/${new_string}/" /etc/nginx/sites-enabled/default
sudo service nginx restart

